//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\ycchen10\OneDrive - kochind.com\Desktop\MolexPlugIn-12.0\UI\EleProgram.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: ycchen10
//              Version: NX 11
//              Date: 04-10-2020  (Format: mm-dd-yyyy)
//              Time: 18:49 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;
using Basic;
using MolexPlugin.Model;
using MolexPlugin.DAL;

namespace MolexPlugin
{

    //------------------------------------------------------------------------------
    //Represents Block Styler application class
    //------------------------------------------------------------------------------
    public class EleProgram
    {
        //class members
        private static Session theSession = null;
        private static UI theUI = null;
        private string theDlxFileName;
        private NXOpen.BlockStyler.BlockDialog theDialog;
        private NXOpen.BlockStyler.ScrolledWindow scrolledWindow;// Block type: Scrolled Window
        private NXOpen.BlockStyler.Group group;// Block type: Group
        private NXOpen.BlockStyler.Tree tree_eleInfo;// Block type: Tree Control
        private NXOpen.BlockStyler.DoubleBlock double_offestF;// Block type: Double
        private NXOpen.BlockStyler.DoubleBlock double_offestD;// Block type: Double
        private NXOpen.BlockStyler.DoubleBlock double_offsetR;// Block type: Double
        private NXOpen.BlockStyler.Group group2;// Block type: Group
        private NXOpen.BlockStyler.Tree tree_operInfo;// Block type: Tree Control
        private NXOpen.BlockStyler.ScrolledWindow scrolledWindow1;// Block type: Scrolled Window
        private NXOpen.BlockStyler.FolderSelection file;// Block type: NativeFolderBrowser
        private NXOpen.BlockStyler.Group group1;// Block type: Group
        private NXOpen.BlockStyler.ListBox list_box_template;// Block type: List Box
        private NXOpen.BlockStyler.DrawingArea png;// Block type: Drawing Area
        private NXOpen.BlockStyler.Group group3;// Block type: Group
        private NXOpen.BlockStyler.Button button_corner;// Block type: Button
        private NXOpen.BlockStyler.Button button_profile;// Block type: Button
        private NXOpen.BlockStyler.Button button_boundaries;// Block type: Button
        private NXOpen.BlockStyler.Button button_zlevel;// Block type: Button
        private NXOpen.BlockStyler.Button button_fixed;// Block type: Button
        private NXOpen.BlockStyler.Button button_flowcut;// Block type: Button
        private NXOpen.BlockStyler.Group groupParameter;// Block type: Group
        private NXOpen.BlockStyler.Enumeration enumProgram;// Block type: Enumeration
        private NXOpen.BlockStyler.Enumeration enumTool;// Block type: Enumeration
        private NXOpen.BlockStyler.Button buttSele;// Block type: Button
        private NXOpen.BlockStyler.Group group5;// Block type: Group
        private NXOpen.BlockStyler.Toggle togCompute;// Block type: Toggle
        private AssembleModel assemble;
        AbstractElectrodeOperation eleOper;
        private IDisplayObject m_highlight = null;

        //------------------------------------------------------------------------------
        //Constructor for NX Styler class
        //------------------------------------------------------------------------------
        public EleProgram()
        {
            try
            {
                theSession = Session.GetSession();
                theUI = UI.GetUI();
                theDlxFileName = "EleProgram.dlx";
                theDialog = theUI.CreateDialog(theDlxFileName);
                theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
                theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
                theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
                theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
                theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                throw ex;
            }
        }

        //------------------------------------------------------------------------------
        //This method shows the dialog on the screen
        //------------------------------------------------------------------------------
        public NXOpen.UIStyler.DialogResponse Show()
        {
            try
            {
                Part workPart = theSession.Parts.Work;
                string type = AttributeUtils.GetAttrForString(workPart, "PartType");
                if (!type.Equals("ASM", StringComparison.CurrentCultureIgnoreCase))
                {
                    theUI.NXMessageBox.Show("错误", NXMessageBox.DialogType.Error, "请切换到ASM档");
                    return 0;
                }
                MoldInfoModel info = new MoldInfoModel(workPart);
                string name = info.MoldNumber + "-" + info.WorkpieceNumber;
                assemble = AssembleSingleton.Instance().GetAssemble(name);
                theDialog.Show();
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Method Name: Dispose
        //------------------------------------------------------------------------------
        public void Dispose()
        {
            if (theDialog != null)
            {
                theDialog.Dispose();
                theDialog = null;
            }
        }

        //------------------------------------------------------------------------------
        //---------------------Block UI Styler Callback Functions--------------------------
        //------------------------------------------------------------------------------

        //------------------------------------------------------------------------------
        //Callback Name: initialize_cb
        //------------------------------------------------------------------------------
        public void initialize_cb()
        {
            try
            {
                scrolledWindow = (NXOpen.BlockStyler.ScrolledWindow)theDialog.TopBlock.FindBlock("scrolledWindow");
                group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
                tree_eleInfo = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("tree_eleInfo");
                double_offestF = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_offestF");
                double_offestD = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_offestD");
                double_offsetR = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("double_offsetR");
                group2 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group2");
                tree_operInfo = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("tree_operInfo");
                scrolledWindow1 = (NXOpen.BlockStyler.ScrolledWindow)theDialog.TopBlock.FindBlock("scrolledWindow1");
                file = (NXOpen.BlockStyler.FolderSelection)theDialog.TopBlock.FindBlock("file");
                group1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group1");
                list_box_template = (NXOpen.BlockStyler.ListBox)theDialog.TopBlock.FindBlock("list_box_template");
                png = (NXOpen.BlockStyler.DrawingArea)theDialog.TopBlock.FindBlock("png");
                group3 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group3");
                button_corner = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_corner");
                button_profile = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_profile");
                button_boundaries = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_boundaries");
                button_zlevel = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_zlevel");
                button_fixed = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_fixed");
                button_flowcut = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button_flowcut");
                groupParameter = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("groupParameter");
                enumProgram = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enumProgram");
                enumTool = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enumTool");
                buttSele = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("buttSele");
                group5 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group5");
                togCompute = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("togCompute");




                #region 回调函数
                //------------------------------------------------------------------------------
                //Registration of Treelist specific callbacks
                //------------------------------------------------------------------------------
                //tree_eleInfo.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));

                //tree_eleInfo.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));

                //tree_eleInfo.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));

                //tree_eleInfo.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));

                //tree_eleInfo.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));

                tree_eleInfo.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));

                //tree_eleInfo.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));

                //tree_eleInfo.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));

                //tree_eleInfo.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));

                //tree_eleInfo.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));

                //tree_eleInfo.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));

                //tree_eleInfo.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));

                //tree_eleInfo.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));

                //tree_eleInfo.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));

                tree_eleInfo.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback)); ;

                tree_eleInfo.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback)); ;

                //tree_eleInfo.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;

                //tree_eleInfo.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;

                //tree_eleInfo.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;

                //tree_eleInfo.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));

                //tree_eleInfo.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));

                //tree_operInfo.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));

                //tree_operInfo.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));

                //tree_operInfo.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));

                //tree_operInfo.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));

                //tree_operInfo.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));

                //tree_operInfo.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));

                //tree_operInfo.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));

                //tree_operInfo.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));

                //tree_operInfo.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));

                //tree_operInfo.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));

                //tree_operInfo.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));

                //tree_operInfo.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));

                //tree_operInfo.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));

                //tree_operInfo.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));

                //tree_operInfo.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback));;

                //tree_operInfo.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback));;

                //tree_operInfo.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;

                //tree_operInfo.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;

                //tree_operInfo.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;

                //tree_operInfo.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));

                //tree_operInfo.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));

                //------------------------------------------------------------------------------
                //------------------------------------------------------------------------------
                //Registration of ListBox specific callbacks
                //------------------------------------------------------------------------------
                //list_box_template.SetAddHandler(new NXOpen.BlockStyler.ListBox.AddCallback(AddCallback));

                //list_box_template.SetDeleteHandler(new NXOpen.BlockStyler.ListBox.DeleteCallback(DeleteCallback));

                //------------------------------------------------------------------------------
                #endregion

                this.double_offestD.Show = false;
                this.double_offestF.Show = false;
                this.double_offsetR.Show = false;
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: dialogShown_cb
        //This callback is executed just before the dialog launch. Thus any value set 
        //here will take precedence and dialog will be launched showing that value. 
        //------------------------------------------------------------------------------
        public void dialogShown_cb()
        {
            try
            {
                //---- Enter your callback code here -----
                SetEleTreeTitle();
                SetOperTreeTitle();
                AddEleToTree();
                AddOperTree();

            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: apply_cb
        //------------------------------------------------------------------------------
        public int apply_cb()
        {
            int errorCode = 0;
            try
            {
                //---- Enter your callback code here -----
                this.eleOper.CreateOperation(false);
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Callback Name: update_cb
        //------------------------------------------------------------------------------
        public int update_cb(NXOpen.BlockStyler.UIBlock block)
        {
            try
            {
                if (block == double_offestF)
                {
                    //---------Enter your code here-----------
                }
                else if (block == double_offestD)
                {
                    //---------Enter your code here-----------
                }
                else if (block == double_offsetR)
                {
                    //---------Enter your code here-----------
                }
                else if (block == file)
                {
                    //---------Enter your code here-----------
                }
                else if (block == list_box_template)
                {
                    //---------Enter your code here-----------
                }
                else if (block == png)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_corner)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_profile)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_boundaries)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_zlevel)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_fixed)
                {
                    //---------Enter your code here-----------
                }
                else if (block == button_flowcut)
                {
                    //---------Enter your code here-----------
                }
                else if (block == enumProgram)
                {
                    //---------Enter your code here-----------
                }
                else if (block == enumTool)
                {
                    //---------Enter your code here-----------
                }
                else if (block == buttSele)
                {
                    //---------Enter your code here-----------
                }
                else if (block == togCompute)
                {
                    //---------Enter your code here-----------
                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Callback Name: ok_cb
        //------------------------------------------------------------------------------
        public int ok_cb()
        {
            int errorCode = 0;
            try
            {
                errorCode = apply_cb();
                //---- Enter your callback code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }
        //------------------------------------------------------------------------------
        //Treelist specific callbacks
        //------------------------------------------------------------------------------
        //public void OnExpandCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnInsertColumnCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public void OnInsertNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnDeleteNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnPreSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
        //{
        //}

        public void OnSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
        {
            if (tree.Equals(tree_eleInfo))
            {
                if (m_highlight != null)
                    m_highlight.Highlight(false);
                foreach (ElectrodeModel ele in assemble.Electrodes)
                {
                    if (ele.Node.Equals(node))
                    {
                        m_highlight = ele;
                        m_highlight.Highlight(true);
                    }
                }
            }

        }

        //public void OnStateChangecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int State)
        //{
        //}

        //public string ToolTipTextcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public int ColumnSortcallback(NXOpen.BlockStyler.Tree tree, int columnID, NXOpen.BlockStyler.Node node1, NXOpen.BlockStyler.Node node2)
        //{
        //}

        //public string StateIconNameCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int state)
        //{
        //}

        //public Tree.BeginLabelEditState OnBeginLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public Tree.EndLabelEditState OnEndLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, string editedText)
        //{
        //}

        //public Tree.EditControlOption OnEditOptionSelectedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, int selectedOptionID, string selectedOptionText, Tree.ControlType type)
        //{
        //}

        //public Tree.ControlType AskEditControlCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        public void OnMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        {
            TreeListMenu menu = this.tree_eleInfo.CreateMenu();
            menu.AddMenuItem(1, "删除", "delete_sc");
            this.tree_eleInfo.SetMenu(menu);
        }

        public void OnMenuSelectionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int menuItemID)
        {
            this.tree_eleInfo.DeleteNode(node);
        }

        //public Node.DropType IsDropAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
        //{
        //}

        //public Node.DragType IsDragAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public bool OnDropCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node[] node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID, Node.DropType dropType, int dropMenuItemId)
        //{
        //}

        //public void OnDropMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
        //{
        //}

        //public void OnDefaultActionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //------------------------------------------------------------------------------
        //ListBox specific callbacks
        //------------------------------------------------------------------------------
        //public int  AddCallback (NXOpen.BlockStyler.ListBox list_box)
        //{
        //}

        //public int  DeleteCallback(NXOpen.BlockStyler.ListBox list_box)
        //{
        //}

        //------------------------------------------------------------------------------

        //------------------------------------------------------------------------------
        //Function Name: GetBlockProperties
        //Returns the propertylist of the specified BlockID
        //------------------------------------------------------------------------------
        public PropertyList GetBlockProperties(string blockID)
        {
            PropertyList plist = null;
            try
            {
                plist = theDialog.GetBlockProperties(blockID);
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return plist;
        }
        /// <summary>
        /// 设置电极树列
        /// </summary>
        private void SetEleTreeTitle()
        {
            this.tree_eleInfo.InsertColumn(0, "电极名", 153);
            this.tree_eleInfo.InsertColumn(1, "电极类型", 80);
            this.tree_eleInfo.InsertColumn(2, "粗间隙", 80);
            this.tree_eleInfo.InsertColumn(3, "中间隙", 80);
            this.tree_eleInfo.InsertColumn(4, "精间隙", 80);
        }
        /// <summary>
        /// 设置刀路列
        /// </summary>
        private void SetOperTreeTitle()
        {
            this.tree_operInfo.InsertColumn(0, "程序名", 160);
            this.tree_operInfo.InsertColumn(1, "刀具名", 100);
            this.tree_operInfo.InsertColumn(2, "刀路名", 100);
        }
        /// <summary>
        /// 设置电极行
        /// </summary>
        private void AddEleToTree()
        {
            assemble.Electrodes.Sort();
            foreach (ElectrodeModel ele in assemble.Electrodes)
            {

                Node pNode = this.tree_eleInfo.CreateNode(ele.EleInfo.EleName);
                this.tree_eleInfo.InsertNode(pNode, null, null, Tree.NodeInsertOption.Last);
                pNode.SetColumnDisplayText(0, ele.EleInfo.EleName);
                pNode.SetColumnDisplayText(1, ele.EleInfo.EleType);
                pNode.SetColumnDisplayText(2, ele.EleInfo.CrudeInter.ToString());
                pNode.SetColumnDisplayText(3, ele.EleInfo.DuringInter.ToString());
                pNode.SetColumnDisplayText(4, ele.EleInfo.FineInter.ToString());
                ele.Node = pNode;
            }
        }

        public void AddOperTree()
        {
            eleOper = new SimplenessVerticalEleOperation(assemble.Electrodes[0], false);
            eleOper.CreateOperationNameModel();
            foreach (AbstractCreateOperation ao in eleOper.Oper)
            {
                Node pNode = this.tree_operInfo.CreateNode(ao.NameModel.OperName);
                this.tree_operInfo.InsertNode(pNode, null, null, Tree.NodeInsertOption.Last);
                pNode.SetColumnDisplayText(0, ao.NameModel.ProgramName);
                pNode.SetColumnDisplayText(1, ao.NameModel.ToolName);
                pNode.SetColumnDisplayText(2, ao.NameModel.OperName);
            }
        }
    }
}
